### ISSUE TITLE
Run directly at Android

### ISSUE THREAD

**Issue by Fabioni** [SimonAlling/userscript-proxy#10] opened 2021-06-14 05:53 UTC
Hey,

Wouldn't it be possible to run this program somehow directly on the phone to avoid the way over a third device and the need to be in my home wifi?

**Comment by SimonAlling** [comment] 2021-06-15 22:24
Hello and welcome to the repo!

I believe this is a duplicate of #3.

**Closed** 2021-08-29 20:31 UTC
Labels: duplicate
